/* World Capitals Quiz — dataset
   Capitals reflect current official status as of August 2026, including
   recent changes (e.g. Equatorial Guinea, Jan 2026) and notable exceptions
   where the "capital" is contested, split, or in transition. */

function flagEmoji(cc) {
  if (!cc || cc.length !== 2) return "🏳️";
  return String.fromCodePoint(
    ...cc.toUpperCase().split("").map((c) => 127397 + c.charCodeAt(0))
  );
}

const COUNTRIES = [
  // ---------------- AFRICA ----------------
  { country: "Algeria", capital: "Algiers", cc: "DZ", region: "Africa" },
  { country: "Angola", capital: "Luanda", cc: "AO", region: "Africa" },
  { country: "Benin", capital: "Porto-Novo", cc: "BJ", region: "Africa", alt: ["porto novo"], note: "Porto-Novo is the official capital, but Cotonou is the seat of government and largest city." },
  { country: "Botswana", capital: "Gaborone", cc: "BW", region: "Africa" },
  { country: "Burkina Faso", capital: "Ouagadougou", cc: "BF", region: "Africa" },
  { country: "Burundi", capital: "Gitega", cc: "BI", region: "Africa", note: "Gitega replaced Bujumbura as the political capital in 2019; Bujumbura remains the economic capital." },
  { country: "Cabo Verde", capital: "Praia", cc: "CV", region: "Africa", alt: ["cape verde"] },
  { country: "Cameroon", capital: "Yaoundé", cc: "CM", region: "Africa", alt: ["yaounde"] },
  { country: "Central African Republic", capital: "Bangui", cc: "CF", region: "Africa" },
  { country: "Chad", capital: "N'Djamena", cc: "TD", region: "Africa", alt: ["ndjamena", "n djamena"] },
  { country: "Comoros", capital: "Moroni", cc: "KM", region: "Africa" },
  { country: "Republic of the Congo", capital: "Brazzaville", cc: "CG", region: "Africa", alt: ["congo", "congo-brazzaville"] },
  { country: "DR Congo", capital: "Kinshasa", cc: "CD", region: "Africa", alt: ["democratic republic of the congo", "congo-kinshasa", "drc"] },
  { country: "Djibouti", capital: "Djibouti City", cc: "DJ", region: "Africa", alt: ["djibouti"] },
  { country: "Egypt", capital: "Cairo", cc: "EG", region: "Africa", watch: "As of 2026, Egypt has relocated its parliament and all 34 ministries to the New Administrative Capital ('The New Capital'), ~45 km east of Cairo — but Cairo remains the recognized capital for now." },
  { country: "Equatorial Guinea", capital: "Ciudad de la Paz", cc: "GQ", region: "Africa", alt: ["malabo"], changed: "Ciudad de la Paz officially replaced Malabo as the capital on 2 January 2026, after nearly two decades of construction on the mainland." },
  { country: "Eritrea", capital: "Asmara", cc: "ER", region: "Africa" },
  { country: "Eswatini", capital: "Mbabane", cc: "SZ", region: "Africa", note: "Mbabane is the administrative capital; nearby Lobamba is the royal and legislative capital." },
  { country: "Ethiopia", capital: "Addis Ababa", cc: "ET", region: "Africa" },
  { country: "Gabon", capital: "Libreville", cc: "GA", region: "Africa" },
  { country: "Gambia", capital: "Banjul", cc: "GM", region: "Africa" },
  { country: "Ghana", capital: "Accra", cc: "GH", region: "Africa" },
  { country: "Guinea", capital: "Conakry", cc: "GN", region: "Africa" },
  { country: "Guinea-Bissau", capital: "Bissau", cc: "GW", region: "Africa" },
  { country: "Ivory Coast", capital: "Yamoussoukro", cc: "CI", region: "Africa", alt: ["cote d'ivoire", "côte d'ivoire"], note: "Yamoussoukro is the official capital, but Abidjan remains the economic hub and seat of most government functions." },
  { country: "Kenya", capital: "Nairobi", cc: "KE", region: "Africa" },
  { country: "Lesotho", capital: "Maseru", cc: "LS", region: "Africa" },
  { country: "Liberia", capital: "Monrovia", cc: "LR", region: "Africa" },
  { country: "Libya", capital: "Tripoli", cc: "LY", region: "Africa" },
  { country: "Madagascar", capital: "Antananarivo", cc: "MG", region: "Africa" },
  { country: "Malawi", capital: "Lilongwe", cc: "MW", region: "Africa" },
  { country: "Mali", capital: "Bamako", cc: "ML", region: "Africa" },
  { country: "Mauritania", capital: "Nouakchott", cc: "MR", region: "Africa" },
  { country: "Mauritius", capital: "Port Louis", cc: "MU", region: "Africa" },
  { country: "Morocco", capital: "Rabat", cc: "MA", region: "Africa" },
  { country: "Mozambique", capital: "Maputo", cc: "MZ", region: "Africa" },
  { country: "Namibia", capital: "Windhoek", cc: "NA", region: "Africa" },
  { country: "Niger", capital: "Niamey", cc: "NE", region: "Africa" },
  { country: "Nigeria", capital: "Abuja", cc: "NG", region: "Africa" },
  { country: "Rwanda", capital: "Kigali", cc: "RW", region: "Africa" },
  { country: "São Tomé and Príncipe", capital: "São Tomé", cc: "ST", region: "Africa", alt: ["sao tome"] },
  { country: "Senegal", capital: "Dakar", cc: "SN", region: "Africa" },
  { country: "Seychelles", capital: "Victoria", cc: "SC", region: "Africa" },
  { country: "Sierra Leone", capital: "Freetown", cc: "SL", region: "Africa" },
  { country: "Somalia", capital: "Mogadishu", cc: "SO", region: "Africa" },
  { country: "South Africa", capital: "Pretoria", cc: "ZA", region: "Africa", alt: ["cape town", "bloemfontein"], note: "South Africa uniquely has three capitals: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial)." },
  { country: "South Sudan", capital: "Juba", cc: "SS", region: "Africa", watch: "A planned move to a purpose-built capital at Ramciel has been discussed since 2011 but remains unrealized." },
  { country: "Sudan", capital: "Khartoum", cc: "SD", region: "Africa" },
  { country: "Tanzania", capital: "Dodoma", cc: "TZ", region: "Africa", alt: ["dar es salaam"], note: "Dodoma is the official capital, though Dar es Salaam remains the largest city and commercial center." },
  { country: "Togo", capital: "Lomé", cc: "TG", region: "Africa", alt: ["lome"] },
  { country: "Tunisia", capital: "Tunis", cc: "TN", region: "Africa" },
  { country: "Uganda", capital: "Kampala", cc: "UG", region: "Africa" },
  { country: "Zambia", capital: "Lusaka", cc: "ZM", region: "Africa" },
  { country: "Zimbabwe", capital: "Harare", cc: "ZW", region: "Africa" },

  // ---------------- ASIA ----------------
  { country: "Afghanistan", capital: "Kabul", cc: "AF", region: "Asia" },
  { country: "Armenia", capital: "Yerevan", cc: "AM", region: "Asia" },
  { country: "Azerbaijan", capital: "Baku", cc: "AZ", region: "Asia" },
  { country: "Bahrain", capital: "Manama", cc: "BH", region: "Asia" },
  { country: "Bangladesh", capital: "Dhaka", cc: "BD", region: "Asia" },
  { country: "Bhutan", capital: "Thimphu", cc: "BT", region: "Asia" },
  { country: "Brunei", capital: "Bandar Seri Begawan", cc: "BN", region: "Asia" },
  { country: "Cambodia", capital: "Phnom Penh", cc: "KH", region: "Asia" },
  { country: "China", capital: "Beijing", cc: "CN", region: "Asia" },
  { country: "Cyprus", capital: "Nicosia", cc: "CY", region: "Asia" },
  { country: "Georgia", capital: "Tbilisi", cc: "GE", region: "Asia" },
  { country: "India", capital: "New Delhi", cc: "IN", region: "Asia" },
  { country: "Indonesia", capital: "Jakarta", cc: "ID", region: "Asia", watch: "Indonesia's Constitutional Court has confirmed Jakarta remains the legal capital. The new city of Nusantara, on Borneo, is being scaled back to serve only as a 'political capital' from roughly 2028, hosting the presidency and legislature." },
  { country: "Iran", capital: "Tehran", cc: "IR", region: "Asia" },
  { country: "Iraq", capital: "Baghdad", cc: "IQ", region: "Asia" },
  { country: "Israel", capital: "Jerusalem", cc: "IL", region: "Asia", note: "Israel designates Jerusalem as its capital, though this is not universally recognized internationally; most countries maintain embassies in Tel Aviv." },
  { country: "Japan", capital: "Tokyo", cc: "JP", region: "Asia" },
  { country: "Jordan", capital: "Amman", cc: "JO", region: "Asia" },
  { country: "Kazakhstan", capital: "Astana", cc: "KZ", region: "Asia", alt: ["nur-sultan", "nursultan"], note: "The city was renamed Nur-Sultan in 2019 in honor of the former president, then reverted to its original name, Astana, in 2022." },
  { country: "Kuwait", capital: "Kuwait City", cc: "KW", region: "Asia", alt: ["kuwait"] },
  { country: "Kyrgyzstan", capital: "Bishkek", cc: "KG", region: "Asia" },
  { country: "Laos", capital: "Vientiane", cc: "LA", region: "Asia" },
  { country: "Lebanon", capital: "Beirut", cc: "LB", region: "Asia" },
  { country: "Malaysia", capital: "Kuala Lumpur", cc: "MY", region: "Asia", alt: ["putrajaya"], note: "Kuala Lumpur is the official capital, while Putrajaya, built in the 1990s, hosts most federal administrative offices." },
  { country: "Maldives", capital: "Malé", cc: "MV", region: "Asia", alt: ["male"] },
  { country: "Mongolia", capital: "Ulaanbaatar", cc: "MN", region: "Asia" },
  { country: "Myanmar", capital: "Naypyidaw", cc: "MM", region: "Asia", note: "The military government abruptly moved the capital from Yangon to the purpose-built city of Naypyidaw in 2005." },
  { country: "Nepal", capital: "Kathmandu", cc: "NP", region: "Asia" },
  { country: "North Korea", capital: "Pyongyang", cc: "KP", region: "Asia" },
  { country: "Oman", capital: "Muscat", cc: "OM", region: "Asia" },
  { country: "Pakistan", capital: "Islamabad", cc: "PK", region: "Asia" },
  { country: "Palestine", capital: "Ramallah", cc: "PS", region: "Asia", note: "Ramallah is the administrative seat of the Palestinian Authority; East Jerusalem is the declared capital, a status disputed internationally." },
  { country: "Philippines", capital: "Manila", cc: "PH", region: "Asia" },
  { country: "Qatar", capital: "Doha", cc: "QA", region: "Asia" },
  { country: "Saudi Arabia", capital: "Riyadh", cc: "SA", region: "Asia" },
  { country: "Singapore", capital: "Singapore", cc: "SG", region: "Asia" },
  { country: "South Korea", capital: "Seoul", cc: "KR", region: "Asia" },
  { country: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", cc: "LK", region: "Asia", alt: ["kotte", "colombo"], note: "Sri Jayawardenepura Kotte is the official legislative capital; nearby Colombo is the commercial capital and most commonly assumed answer." },
  { country: "Syria", capital: "Damascus", cc: "SY", region: "Asia" },
  { country: "Taiwan", capital: "Taipei", cc: "TW", region: "Asia" },
  { country: "Tajikistan", capital: "Dushanbe", cc: "TJ", region: "Asia" },
  { country: "Thailand", capital: "Bangkok", cc: "TH", region: "Asia" },
  { country: "Timor-Leste", capital: "Dili", cc: "TL", region: "Asia", alt: ["east timor"] },
  { country: "Turkey", capital: "Ankara", cc: "TR", region: "Asia", alt: ["türkiye", "turkiye"] },
  { country: "Turkmenistan", capital: "Ashgabat", cc: "TM", region: "Asia" },
  { country: "United Arab Emirates", capital: "Abu Dhabi", cc: "AE", region: "Asia" },
  { country: "Uzbekistan", capital: "Tashkent", cc: "UZ", region: "Asia" },
  { country: "Vietnam", capital: "Hanoi", cc: "VN", region: "Asia" },
  { country: "Yemen", capital: "Sana'a", cc: "YE", region: "Asia", alt: ["sanaa", "aden"], note: "Sana'a is the internationally recognized capital, though the government has operated from Aden amid ongoing conflict." },

  // ---------------- EUROPE ----------------
  { country: "Albania", capital: "Tirana", cc: "AL", region: "Europe" },
  { country: "Andorra", capital: "Andorra la Vella", cc: "AD", region: "Europe" },
  { country: "Austria", capital: "Vienna", cc: "AT", region: "Europe" },
  { country: "Belarus", capital: "Minsk", cc: "BY", region: "Europe" },
  { country: "Belgium", capital: "Brussels", cc: "BE", region: "Europe" },
  { country: "Bosnia and Herzegovina", capital: "Sarajevo", cc: "BA", region: "Europe" },
  { country: "Bulgaria", capital: "Sofia", cc: "BG", region: "Europe" },
  { country: "Croatia", capital: "Zagreb", cc: "HR", region: "Europe" },
  { country: "Czechia", capital: "Prague", cc: "CZ", region: "Europe", alt: ["czech republic"] },
  { country: "Denmark", capital: "Copenhagen", cc: "DK", region: "Europe" },
  { country: "Estonia", capital: "Tallinn", cc: "EE", region: "Europe" },
  { country: "Finland", capital: "Helsinki", cc: "FI", region: "Europe" },
  { country: "France", capital: "Paris", cc: "FR", region: "Europe" },
  { country: "Germany", capital: "Berlin", cc: "DE", region: "Europe" },
  { country: "Greece", capital: "Athens", cc: "GR", region: "Europe" },
  { country: "Hungary", capital: "Budapest", cc: "HU", region: "Europe" },
  { country: "Iceland", capital: "Reykjavik", cc: "IS", region: "Europe" },
  { country: "Ireland", capital: "Dublin", cc: "IE", region: "Europe" },
  { country: "Italy", capital: "Rome", cc: "IT", region: "Europe" },
  { country: "Kosovo", capital: "Pristina", cc: "XK", region: "Europe" },
  { country: "Latvia", capital: "Riga", cc: "LV", region: "Europe" },
  { country: "Liechtenstein", capital: "Vaduz", cc: "LI", region: "Europe" },
  { country: "Lithuania", capital: "Vilnius", cc: "LT", region: "Europe" },
  { country: "Luxembourg", capital: "Luxembourg City", cc: "LU", region: "Europe", alt: ["luxembourg"] },
  { country: "Malta", capital: "Valletta", cc: "MT", region: "Europe" },
  { country: "Moldova", capital: "Chișinău", cc: "MD", region: "Europe", alt: ["chisinau"] },
  { country: "Monaco", capital: "Monaco", cc: "MC", region: "Europe" },
  { country: "Montenegro", capital: "Podgorica", cc: "ME", region: "Europe", alt: ["cetinje"], note: "Podgorica is the official capital; Cetinje retains the ceremonial title 'Old Royal Capital'." },
  { country: "Netherlands", capital: "Amsterdam", cc: "NL", region: "Europe", alt: ["the hague", "hague"], note: "Amsterdam is the constitutional capital, but The Hague is the seat of government, parliament, and the royal residence." },
  { country: "North Macedonia", capital: "Skopje", cc: "MK", region: "Europe" },
  { country: "Norway", capital: "Oslo", cc: "NO", region: "Europe" },
  { country: "Poland", capital: "Warsaw", cc: "PL", region: "Europe" },
  { country: "Portugal", capital: "Lisbon", cc: "PT", region: "Europe" },
  { country: "Romania", capital: "Bucharest", cc: "RO", region: "Europe" },
  { country: "Russia", capital: "Moscow", cc: "RU", region: "Europe" },
  { country: "San Marino", capital: "San Marino", cc: "SM", region: "Europe" },
  { country: "Serbia", capital: "Belgrade", cc: "RS", region: "Europe" },
  { country: "Slovakia", capital: "Bratislava", cc: "SK", region: "Europe" },
  { country: "Slovenia", capital: "Ljubljana", cc: "SI", region: "Europe" },
  { country: "Spain", capital: "Madrid", cc: "ES", region: "Europe" },
  { country: "Sweden", capital: "Stockholm", cc: "SE", region: "Europe" },
  { country: "Switzerland", capital: "Bern", cc: "CH", region: "Europe" },
  { country: "Ukraine", capital: "Kyiv", cc: "UA", region: "Europe", alt: ["kiev"] },
  { country: "United Kingdom", capital: "London", cc: "GB", region: "Europe" },
  { country: "Vatican City", capital: "Vatican City", cc: "VA", region: "Europe" },

  // ---------------- NORTH AMERICA ----------------
  { country: "Antigua and Barbuda", capital: "Saint John's", cc: "AG", region: "North America", alt: ["st johns", "st john's"] },
  { country: "Bahamas", capital: "Nassau", cc: "BS", region: "North America" },
  { country: "Barbados", capital: "Bridgetown", cc: "BB", region: "North America" },
  { country: "Belize", capital: "Belmopan", cc: "BZ", region: "North America" },
  { country: "Canada", capital: "Ottawa", cc: "CA", region: "North America" },
  { country: "Costa Rica", capital: "San José", cc: "CR", region: "North America", alt: ["san jose"] },
  { country: "Cuba", capital: "Havana", cc: "CU", region: "North America" },
  { country: "Dominica", capital: "Roseau", cc: "DM", region: "North America" },
  { country: "Dominican Republic", capital: "Santo Domingo", cc: "DO", region: "North America" },
  { country: "El Salvador", capital: "San Salvador", cc: "SV", region: "North America" },
  { country: "Grenada", capital: "St. George's", cc: "GD", region: "North America", alt: ["st georges", "saint george's"] },
  { country: "Guatemala", capital: "Guatemala City", cc: "GT", region: "North America" },
  { country: "Haiti", capital: "Port-au-Prince", cc: "HT", region: "North America", alt: ["port au prince"] },
  { country: "Honduras", capital: "Tegucigalpa", cc: "HN", region: "North America" },
  { country: "Jamaica", capital: "Kingston", cc: "JM", region: "North America" },
  { country: "Mexico", capital: "Mexico City", cc: "MX", region: "North America" },
  { country: "Nicaragua", capital: "Managua", cc: "NI", region: "North America" },
  { country: "Panama", capital: "Panama City", cc: "PA", region: "North America" },
  { country: "Saint Kitts and Nevis", capital: "Basseterre", cc: "KN", region: "North America" },
  { country: "Saint Lucia", capital: "Castries", cc: "LC", region: "North America" },
  { country: "Saint Vincent and the Grenadines", capital: "Kingstown", cc: "VC", region: "North America" },
  { country: "Trinidad and Tobago", capital: "Port of Spain", cc: "TT", region: "North America" },
  { country: "United States", capital: "Washington, D.C.", cc: "US", region: "North America", alt: ["washington dc", "washington"] },

  // ---------------- SOUTH AMERICA ----------------
  { country: "Argentina", capital: "Buenos Aires", cc: "AR", region: "South America" },
  { country: "Bolivia", capital: "Sucre", cc: "BO", region: "South America", alt: ["la paz"], note: "Sucre is the constitutional capital, but La Paz is the seat of government and the world's highest administrative capital." },
  { country: "Brazil", capital: "Brasília", cc: "BR", region: "South America", alt: ["brasilia"] },
  { country: "Chile", capital: "Santiago", cc: "CL", region: "South America", alt: ["valparaiso", "valparaíso"], note: "Santiago is the capital and seat of government, while the National Congress sits in nearby Valparaíso." },
  { country: "Colombia", capital: "Bogotá", cc: "CO", region: "South America", alt: ["bogota"] },
  { country: "Ecuador", capital: "Quito", cc: "EC", region: "South America" },
  { country: "Guyana", capital: "Georgetown", cc: "GY", region: "South America" },
  { country: "Paraguay", capital: "Asunción", cc: "PY", region: "South America", alt: ["asuncion"] },
  { country: "Peru", capital: "Lima", cc: "PE", region: "South America" },
  { country: "Suriname", capital: "Paramaribo", cc: "SR", region: "South America" },
  { country: "Uruguay", capital: "Montevideo", cc: "UY", region: "South America" },
  { country: "Venezuela", capital: "Caracas", cc: "VE", region: "South America" },

  // ---------------- OCEANIA ----------------
  { country: "Australia", capital: "Canberra", cc: "AU", region: "Oceania", note: "Canberra was purpose-built as a compromise capital between rivals Sydney and Melbourne." },
  { country: "Fiji", capital: "Suva", cc: "FJ", region: "Oceania" },
  { country: "Kiribati", capital: "South Tarawa", cc: "KI", region: "Oceania", alt: ["tarawa"] },
  { country: "Marshall Islands", capital: "Majuro", cc: "MH", region: "Oceania" },
  { country: "Micronesia", capital: "Palikir", cc: "FM", region: "Oceania" },
  { country: "Nauru", capital: "Yaren", cc: "NR", region: "Oceania", note: "Nauru has no official capital; Yaren is the de facto seat of government." },
  { country: "New Zealand", capital: "Wellington", cc: "NZ", region: "Oceania" },
  { country: "Palau", capital: "Ngerulmud", cc: "PW", region: "Oceania", alt: ["koror"], note: "The capital moved from Koror to the purpose-built Ngerulmud in 2006 — one of the world's least populous capitals." },
  { country: "Papua New Guinea", capital: "Port Moresby", cc: "PG", region: "Oceania" },
  { country: "Samoa", capital: "Apia", cc: "WS", region: "Oceania" },
  { country: "Solomon Islands", capital: "Honiara", cc: "SB", region: "Oceania" },
  { country: "Tonga", capital: "Nuku'alofa", cc: "TO", region: "Oceania", alt: ["nukualofa"] },
  { country: "Tuvalu", capital: "Funafuti", cc: "TV", region: "Oceania" },
  { country: "Vanuatu", capital: "Port Vila", cc: "VU", region: "Oceania" },
];

/* Rotating news-banner facts. Each ties to a country by cc for its flag.
   "priority" items (recent/pending capital changes) are woven in throughout. */
const FACTS = [
  { cc: "GQ", country: "Equatorial Guinea", text: "Equatorial Guinea's capital officially moved from Malabo to the newly built Ciudad de la Paz on January 2, 2026 — ending an 18-year construction project." },
  { cc: "ID", country: "Indonesia", text: "Indonesia's Constitutional Court has ruled Jakarta remains the legal capital, even as the new city of Nusantara is scaled back to become a 'political capital' by 2028." },
  { cc: "EG", country: "Egypt", text: "Egypt has relocated its parliament and all 34 government ministries to a still-unnamed New Administrative Capital 45 km east of Cairo." },
  { cc: "KZ", country: "Kazakhstan", text: "Astana was renamed Nur-Sultan in 2019 to honor the former president, then renamed back to Astana in 2022." },
  { cc: "MM", country: "Myanmar", text: "Myanmar's military government secretly moved the capital from Yangon to Naypyidaw overnight in 2005, reportedly on the advice of astrologers." },
  { cc: "PW", country: "Palau", text: "Ngerulmud, Palau's capital since 2006, has a population of roughly 300 — making it one of the smallest national capitals on Earth." },
  { cc: "BR", country: "Brazil", text: "Brasília was built from scratch in just 41 months and became the capital in 1960, laid out in the shape of an airplane." },
  { cc: "AU", country: "Australia", text: "Canberra was purpose-built in 1913 as a compromise capital after Sydney and Melbourne couldn't agree who deserved the title." },
  { cc: "BO", country: "Bolivia", text: "Bolivia has two capitals: Sucre is the constitutional capital, while La Paz — the seat of government — is the highest administrative capital in the world at 3,640 m." },
  { cc: "ZA", country: "South Africa", text: "South Africa splits its capital three ways: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial)." },
  { cc: "NL", country: "Netherlands", text: "Amsterdam is the Netherlands' constitutional capital, but the government, parliament, and king all actually reside in The Hague." },
  { cc: "CI", country: "Ivory Coast", text: "Yamoussoukro has been Ivory Coast's official capital since 1983, yet Abidjan still hosts nearly every embassy and government ministry." },
  { cc: "SZ", country: "Eswatini", text: "Eswatini has two capitals: Mbabane handles administration, while royal and legislative affairs happen in nearby Lobamba." },
  { cc: "VA", country: "Vatican City", text: "Vatican City is both a country and its own capital — the smallest sovereign state in the world at just 0.44 km²." },
  { cc: "SG", country: "Singapore", text: "Singapore is one of only a few city-states where the capital, the city, and the country share the same name and borders." },
  { cc: "SS", country: "South Sudan", text: "South Sudan has discussed relocating its capital from Juba to a purpose-built city at Ramciel since 2011 — the move still hasn't happened." },
  { cc: "LK", country: "Sri Lanka", text: "Sri Lanka's official capital is Sri Jayawardenepura Kotte, though most people — and most maps — point to Colombo instead." },
  { cc: "MY", country: "Malaysia", text: "Kuala Lumpur is Malaysia's official capital, but most federal ministries actually operate from Putrajaya, a planned city built in the 1990s." },
  { cc: "TZ", country: "Tanzania", text: "Dodoma has been Tanzania's official capital since the 1970s, but Dar es Salaam remains the country's largest city and business hub." },
  { cc: "CH", country: "Switzerland", text: "Switzerland has no legally declared 'capital' — Bern is simply the 'federal city' by long-standing convention." },
  { cc: "IL", country: "Israel", text: "Israel designates Jerusalem as its capital, though the city's status is internationally disputed and many countries base embassies in Tel Aviv." },
  { cc: "ME", country: "Montenegro", text: "Podgorica is Montenegro's capital today, but Cetinje still holds the honorary title of 'Old Royal Capital.'" },
  { cc: "CL", country: "Chile", text: "Chile's president governs from Santiago, but its Congress meets 120 km away in the port city of Valparaíso." },
  { cc: "BI", country: "Burundi", text: "Burundi moved its political capital from Bujumbura to Gitega in 2019, while Bujumbura stayed the economic capital." },
  { cc: "NR", country: "Nauru", text: "Nauru is one of the few countries with no official capital city at all — Yaren functions as the de facto seat of government." },
  { cc: "BT", country: "Bhutan", text: "Thimphu is the only national capital in the world without a single traffic light — intersections are managed by hand." },
  { cc: "IS", country: "Iceland", text: "Reykjavik is the world's northernmost capital of a sovereign state." },
  { cc: "MN", country: "Mongolia", text: "Ulaanbaatar is the coldest national capital on Earth, with average temperatures below freezing for much of the year." },
  { cc: "PE", country: "Peru", text: "Lima is one of the driest capital cities in the world, sitting on the edge of the Atacama coastal desert." },
  { cc: "CA", country: "Canada", text: "Ottawa was chosen as Canada's capital in 1857 by Queen Victoria, partly because it sat safely inland from the U.S. border." },
  { cc: "IN", country: "India", text: "New Delhi was inaugurated as India's capital in 1931, replacing Calcutta (now Kolkata), which had served for over a century." },
  { cc: "RU", country: "Russia", text: "Moscow briefly lost its capital status to St. Petersburg for two centuries, only regaining it in 1918." },
  { cc: "TR", country: "Turkey", text: "Ankara replaced Istanbul as Turkey's capital in 1923, a symbolic break from the Ottoman imperial capital." },
  { cc: "NG", country: "Nigeria", text: "Abuja became Nigeria's capital in 1991, purpose-built to sit at the country's neutral geographic and ethnic center, replacing Lagos." },
  { cc: "KP", country: "North Korea", text: "Pyongyang's name translates roughly to 'flat land,' and the city was almost entirely rebuilt after being leveled in the Korean War." },
  { cc: "AE", country: "United Arab Emirates", text: "Abu Dhabi, not Dubai, is the political capital of the UAE — a common mix-up given Dubai's global visibility." },
  { cc: "GH", country: "Ghana", text: "Accra was a modest coastal trading post before becoming the capital of the first sub-Saharan African country to gain independence, in 1957." },

  // ---- broader facts: food, culture, nature, current events ----
  { cc: "DZ", country: "Algeria", text: "Algeria is Africa's largest country by area, with more than 80% of its territory covered by the Sahara Desert." },
  { cc: "BJ", country: "Benin", text: "Benin is considered the birthplace of Vodun, a religion still practiced by millions and marked by its own national holiday each January." },
  { cc: "BW", country: "Botswana", text: "Botswana has set aside nearly 40% of its land for wildlife conservation, giving it one of the largest elephant populations on Earth." },
  { cc: "CV", country: "Cabo Verde", text: "Cabo Verdean cuisine blends Portuguese and West African flavors around cachupa, a slow-cooked corn and bean stew." },
  { cc: "CM", country: "Cameroon", text: "Cameroon is nicknamed 'Africa in miniature' for containing nearly every climate on the continent, from desert to rainforest to snow-capped peaks." },
  { cc: "KM", country: "Comoros", text: "Comoros produces most of the world's ylang-ylang, a fragrant flower oil prized by the perfume industry." },
  { cc: "ET", country: "Ethiopia", text: "Ethiopia runs on its own calendar, roughly seven to eight years behind the Gregorian one, and is widely regarded as the birthplace of coffee." },
  { cc: "GA", country: "Gabon", text: "Gabon has protected over 10% of its territory as national parks, including forest elephants that wander directly onto Atlantic beaches." },
  { cc: "GM", country: "Gambia", text: "The Gambia is mainland Africa's smallest country, a narrow strip of land hugging both banks of the Gambia River." },
  { cc: "GN", country: "Guinea", text: "Guinea holds some of the largest bauxite reserves on Earth, the ore refined into most of the world's aluminum." },
  { cc: "KE", country: "Kenya", text: "Kenya's Maasai Mara hosts the Great Migration each year, when over a million wildebeest cross into Tanzania's Serengeti." },
  { cc: "LS", country: "Lesotho", text: "Lesotho is one of only three countries in the world completely surrounded by a single other country — in its case, South Africa." },
  { cc: "LR", country: "Liberia", text: "Liberia was founded in the 1820s by freed African-American settlers and modeled its flag after that of the United States." },
  { cc: "LY", country: "Libya", text: "Libya holds the largest proven oil reserves in Africa, and the Sahara covers roughly 90% of the country." },
  { cc: "MG", country: "Madagascar", text: "Madagascar split from mainland Africa so long ago that over 90% of its wildlife, including its lemurs, exists nowhere else on Earth." },
  { cc: "MA", country: "Morocco", text: "In Morocco, mint tea is poured from a height to create foam and is traditionally served to guests three times as a mark of hospitality." },
  { cc: "MZ", country: "Mozambique", text: "Mozambique's coastline stretches over 2,500 km along the Indian Ocean, home to some of Africa's richest coral reefs." },
  { cc: "NA", country: "Namibia", text: "Namibia's Namib Desert is believed to be the oldest desert in the world, with some of the tallest sand dunes on Earth." },
  { cc: "RW", country: "Rwanda", text: "Rwanda banned plastic bags nationwide and holds a mandatory monthly community clean-up morning called Umuganda." },
  { cc: "SN", country: "Senegal", text: "Senegal's capital Dakar gave its name to the famous Dakar Rally, even though the race hasn't crossed Africa since 2008." },
  { cc: "SC", country: "Seychelles", text: "Seychelles is home to the Coco de Mer, a palm tree that produces the largest and heaviest seed in the entire plant kingdom." },
  { cc: "SL", country: "Sierra Leone", text: "Sierra Leone's capital Freetown was founded in 1792 as a settlement for freed slaves, giving the country its name." },
  { cc: "SO", country: "Somalia", text: "Somalia has the longest coastline of any mainland African country, stretching along both the Gulf of Aden and the Indian Ocean." },
  { cc: "TG", country: "Togo", text: "Togo is one of the narrowest countries in the world, just 55 km wide at its narrowest point." },
  { cc: "TN", country: "Tunisia", text: "Tunisia's ancient city of Carthage, founded by Phoenician settlers, once rivaled Rome for control of the Mediterranean." },
  { cc: "UG", country: "Uganda", text: "Uganda is home to roughly half of the world's remaining mountain gorillas, protected in Bwindi Impenetrable Forest." },
  { cc: "ZM", country: "Zambia", text: "Zambia and Zimbabwe share Victoria Falls, known locally as 'Mosi-oa-Tunya' — the smoke that thunders." },
  { cc: "ZW", country: "Zimbabwe", text: "Zimbabwe takes its modern name from the Great Zimbabwe ruins, a stone city built without mortar in the 11th century." },
  { cc: "MR", country: "Mauritania", text: "Mauritania stretches across the Sahara and is one of the last places where camel caravans still carry salt across the desert." },
  { cc: "MU", country: "Mauritius", text: "Mauritius was the only known home of the dodo bird, extinct by the late 1600s and now a national symbol." },

  { cc: "AM", country: "Armenia", text: "Armenia claims to be the first nation to adopt Christianity as a state religion, in the early 4th century." },
  { cc: "AZ", country: "Azerbaijan", text: "Azerbaijan is nicknamed the 'Land of Fire' for natural gas seeps that have kept flames burning on its hillsides for centuries." },
  { cc: "BD", country: "Bangladesh", text: "Bangladesh sits atop the world's largest river delta, formed where the Ganges and Brahmaputra rivers meet the Bay of Bengal." },
  { cc: "BN", country: "Brunei", text: "Brunei's rainforests are so intact that roughly three-quarters of the country remains covered in old-growth jungle." },
  { cc: "KH", country: "Cambodia", text: "Cambodia's Angkor Wat is the largest religious monument on Earth, built first as a Hindu temple before becoming a Buddhist site." },
  { cc: "CN", country: "China", text: "China has more UNESCO World Heritage Sites than almost any other country, spanning the Great Wall to the Terracotta Army." },
  { cc: "GE", country: "Georgia", text: "Archaeologists have traced winemaking in Georgia back roughly 8,000 years, among the oldest wine traditions on Earth." },
  { cc: "JP", country: "Japan", text: "Japan has millions of vending machines dotting its streets, selling everything from hot ramen to fresh eggs." },
  { cc: "JO", country: "Jordan", text: "Jordan's ancient city of Petra was carved directly into rose-colored sandstone cliffs over 2,000 years ago." },
  { cc: "KW", country: "Kuwait", text: "The Kuwaiti dinar is consistently ranked among the highest-valued currency units in the world." },
  { cc: "LA", country: "Laos", text: "Laos remains one of the most heavily bombed countries per capita in history, and is still clearing unexploded ordnance today." },
  { cc: "LB", country: "Lebanon", text: "Lebanon's cedar tree, a national symbol for millennia, is featured at the center of the country's flag." },
  { cc: "MV", country: "Maldives", text: "The Maldives is the world's lowest-lying country, with an average elevation of only about 1.5 meters above sea level." },
  { cc: "NP", country: "Nepal", text: "Nepal is home to eight of the world's ten tallest mountains, including Mount Everest." },
  { cc: "OM", country: "Oman", text: "Oman has been ruled by the same family dynasty for over 250 years and was historically a major frankincense trading power." },
  { cc: "PH", country: "Philippines", text: "The Philippines is made up of more than 7,600 islands scattered across the western Pacific." },
  { cc: "QA", country: "Qatar", text: "Qatar hosted the first FIFA World Cup held in the Middle East, in 2022, in stadiums built almost entirely from scratch." },
  { cc: "SA", country: "Saudi Arabia", text: "Saudi Arabia is set to host the FIFA World Cup in 2034, part of a wave of investment into futuristic new cities like NEOM." },
  { cc: "KR", country: "South Korea", text: "South Korea's 'Hallyu,' or Korean Wave, has turned K-pop and K-dramas into one of its biggest cultural exports." },
  { cc: "TH", country: "Thailand", text: "Thailand was the only Southeast Asian nation never colonized by a European power." },
  { cc: "VN", country: "Vietnam", text: "Vietnam is the world's second-largest coffee exporter, prized for its strong, sweetened cà phê sữa đá." },
  { cc: "IR", country: "Iran", text: "Iran's Nowruz, or Persian New Year, is celebrated at the spring equinox and predates Islam by thousands of years." },
  { cc: "PK", country: "Pakistan", text: "Pakistan is home to K2, the world's second-highest peak, and to five of the fourteen mountains over 8,000 meters." },
  { cc: "AF", country: "Afghanistan", text: "Afghanistan sits at the crossroads of the ancient Silk Road and is home to the turquoise-blue lakes of Band-e-Amir, its first national park." },
  { cc: "UZ", country: "Uzbekistan", text: "Uzbekistan's Samarkand was one of the great cities of the Silk Road, famed for its turquoise-tiled Registan square." },

  { cc: "AT", country: "Austria", text: "Vienna has ranked among the world's most livable cities for years running, prized for its imperial architecture and coffeehouse culture." },
  { cc: "BE", country: "Belgium", text: "Belgium brews over 1,500 varieties of beer and has one of the highest concentrations of chocolatiers anywhere in the world." },
  { cc: "BG", country: "Bulgaria", text: "Bulgaria is one of the world's largest producers of rose oil, harvested each spring in its famed Rose Valley." },
  { cc: "HR", country: "Croatia", text: "Croatia's Adriatic coast includes over a thousand islands, and the necktie is believed to trace back to 17th-century Croatian soldiers." },
  { cc: "CZ", country: "Czechia", text: "Czechia has the highest beer consumption per capita in the world, a tradition tied to Prague's centuries-old brewing history." },
  { cc: "DK", country: "Denmark", text: "Denmark regularly ranks among the world's happiest countries and popularized the cozy concept of 'hygge.'" },
  { cc: "EE", country: "Estonia", text: "Estonia was one of the first countries to offer nationwide online voting, and runs the vast majority of public services digitally." },
  { cc: "FI", country: "Finland", text: "Finland has more saunas than cars for its population, and has topped global happiness rankings for years running." },
  { cc: "FR", country: "France", text: "France is the world's most-visited country, and a 1993 law still defines exactly what may go into a traditional baguette." },
  { cc: "DE", country: "Germany", text: "Germany has more than 20,000 castles scattered across the country and over a thousand distinct types of sausage." },
  { cc: "GR", country: "Greece", text: "Greece produces some of the world's most awarded olive oil, a tradition stretching back over 3,000 years." },
  { cc: "HU", country: "Hungary", text: "Hungarian is unrelated to nearly every neighboring language, sharing its closest distant roots with Finnish and Estonian." },
  { cc: "IE", country: "Ireland", text: "Ireland's Book of Kells, an illuminated manuscript from around 800 AD, is one of the most famous surviving medieval texts in the world." },
  { cc: "IT", country: "Italy", text: "Italy has more UNESCO World Heritage Sites than any other country, and co-hosted the 2026 Winter Olympics across Milan and Cortina." },
  { cc: "LV", country: "Latvia", text: "Latvia's capital Riga holds one of the best-preserved collections of Art Nouveau architecture anywhere in Europe." },
  { cc: "LU", country: "Luxembourg", text: "Luxembourg made all public transportation free nationwide in 2020, the first country in the world to do so." },
  { cc: "MT", country: "Malta", text: "Malta's capital Valletta is so densely packed with historic architecture that the entire city is a single UNESCO World Heritage Site." },
  { cc: "NO", country: "Norway", text: "Norway's far north sees the midnight sun each summer, when the sun never fully sets for weeks at a time." },
  { cc: "PL", country: "Poland", text: "Poland's Białowieża Forest is one of the last surviving fragments of the primeval forest that once covered all of Europe." },
  { cc: "PT", country: "Portugal", text: "Portugal is the world's largest cork producer, harvesting bark from trees that can live for centuries without being cut down." },
  { cc: "ES", country: "Spain", text: "Spain eats dinner later than almost anywhere else in Europe, often after 9pm, a quirk tied to its unusual time zone." },
  { cc: "SE", country: "Sweden", text: "Sweden popularized 'fika,' a daily coffee-and-pastry break treated as an essential part of the workday." },
  { cc: "UA", country: "Ukraine", text: "Ukraine is one of the world's largest grain exporters and has long been called the 'breadbasket of Europe.'" },
  { cc: "GB", country: "United Kingdom", text: "London's Underground, opened in 1863, is the oldest metro system in the world." },

  { cc: "BS", country: "Bahamas", text: "The Bahamas is home to Big Major Cay, an uninhabited island famous for its beach-swimming wild pigs." },
  { cc: "CR", country: "Costa Rica", text: "Costa Rica abolished its military in 1948 and now generates almost all of its electricity from renewable sources." },
  { cc: "CU", country: "Cuba", text: "Cuba's classic American cars from the 1950s still cruise Havana's streets, kept running for decades under a long trade embargo." },
  { cc: "DO", country: "Dominican Republic", text: "The Dominican Republic shares the island of Hispaniola with Haiti and is one of the world's top producers of premium cigars." },
  { cc: "GT", country: "Guatemala", text: "Guatemala sits in the region where the ancient Maya first cultivated cacao, giving the world chocolate over 2,500 years ago." },
  { cc: "HT", country: "Haiti", text: "Haiti became the world's first Black-led republic in 1804, following the only fully successful slave revolt in modern history." },
  { cc: "JM", country: "Jamaica", text: "Jamaican reggae, born in Kingston in the 1960s, is recognized by UNESCO as part of humanity's cultural heritage." },
  { cc: "MX", country: "Mexico", text: "Mexico's Day of the Dead celebration is recognized by UNESCO, and the region is credited with giving the world chocolate and vanilla." },
  { cc: "PA", country: "Panama", text: "The Panama Canal, completed in 1914, cuts the sea journey between the Atlantic and Pacific by thousands of nautical miles." },
  { cc: "TT", country: "Trinidad and Tobago", text: "Trinidad and Tobago is the birthplace of the steelpan, often called the only major acoustic instrument invented in the 20th century." },
  { cc: "US", country: "United States", text: "The United States is co-hosting the 2026 FIFA World Cup alongside Canada and Mexico, the first tournament shared by three nations." },
  { cc: "AR", country: "Argentina", text: "Argentines drink more mate than coffee, sharing the bitter herbal tea from a single gourd passed around a circle of friends." },
  { cc: "CO", country: "Colombia", text: "Colombia is one of the most biodiverse countries on Earth and one of the world's largest producers of emeralds." },
  { cc: "EC", country: "Ecuador", text: "Ecuador's Galápagos Islands inspired Charles Darwin's theory of evolution and remain home to giant tortoises found nowhere else." },
  { cc: "PY", country: "Paraguay", text: "Paraguay is one of the few countries where an indigenous language, Guaraní, is co-official and spoken by most of the population." },
  { cc: "SR", country: "Suriname", text: "Suriname has the highest percentage of forest cover of any country on Earth, with over 90% still under rainforest." },
  { cc: "UY", country: "Uruguay", text: "Uruguay generates around 98% of its electricity from renewable sources and was among the first countries to legalize cannabis nationally." },
  { cc: "VE", country: "Venezuela", text: "Venezuela is home to Angel Falls, the world's tallest uninterrupted waterfall, dropping nearly a kilometer." },
  { cc: "HN", country: "Honduras", text: "Honduras hosts part of the Mesoamerican Barrier Reef, the second-largest coral reef system on Earth." },
  { cc: "BB", country: "Barbados", text: "Barbados is considered the birthplace of rum distillation, dating back to its 17th-century sugar plantations." },

  { cc: "FJ", country: "Fiji", text: "Fiji is made up of more than 330 islands, only about a third of which are inhabited." },
  { cc: "NZ", country: "New Zealand", text: "New Zealand was the first country in the world to grant women the right to vote nationally, in 1893." },
  { cc: "PG", country: "Papua New Guinea", text: "Papua New Guinea is the most linguistically diverse country on Earth, home to more than 800 distinct languages." },
  { cc: "WS", country: "Samoa", text: "Samoa switched sides of the International Date Line in 2011, skipping December 30 entirely to align with its main trading partners." },
  { cc: "TO", country: "Tonga", text: "Tonga is the only Pacific nation never formally colonized by a European power and still has a reigning monarchy today." },
  { cc: "TV", country: "Tuvalu", text: "Tuvalu, one of the world's smallest and lowest-lying countries, has explored building a digital archive of itself amid rising seas." },
  { cc: "VU", country: "Vanuatu", text: "Vanuatu is home to Mount Yasur, one of the world's most accessible active volcanoes, where visitors can look directly into its lava lake." },
  { cc: "KI", country: "Kiribati", text: "Kiribati is often cited as the only country in the world situated across all four hemispheres, straddling both the equator and the date line." },
];

const REGIONS = ["Africa", "Asia", "Europe", "North America", "South America", "Oceania"];

/* Data freshness tracking. Updated by the monthly automated verification
   pass — see CHANGELOG for a history of what's changed and when. */
const LAST_VERIFIED = "2026-08-25";

const CHANGELOG = [
  {
    date: "2026-08-25",
    text: "Initial dataset compiled and verified: 197 countries, including Equatorial Guinea's January 2026 capital move to Ciudad de la Paz and the current status of Indonesia's Nusantara transition.",
  },
];
